apiVersion: v1
kind: Service
metadata:
  name: task-postgres
  namespace: task-ns
spec:
  selector:
    app: task-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  clusterIP: None
