apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: gateway-ns
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  Jwt__Issuer: "auth-service-docker"
  Jwt__Audience: "polyglot-platform"
  AuthServiceUrl: "http://auth-service.auth-ns.svc.cluster.local:80"
  TaskServiceUrl: "http://task-service.task-ns.svc.cluster.local:8080"
