apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka-ns
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
    name: kafka
  - protocol: TCP
    port: 8082
    targetPort: 8082
    name: pandaproxy
  - protocol: TCP
    port: 33145
    targetPort: 33145
    name: rpc
  clusterIP: None
