apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: auth-ns
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  Jwt__Issuer: "auth-service-docker"
  Jwt__Audience: "polyglot-platform"
