apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-ns
type: Opaque
stringData:
  jwt-key: docker_supersecretkey_that_is_at_least_32_characters_long
  connection-string: "Host=postgres.auth-ns.svc.cluster.local;Database=authdb;Username=authuser;Password=secret"
