apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
  namespace: devtools-ns
data:
  ME_CONFIG_MONGODB_SERVER: "mongo.analytics-ns.svc.cluster.local"
  ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
  ME_CONFIG_MONGODB_ADMINPASSWORD: "secret"
