apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-worker-task-config
  namespace: analytics-ns
data:
  DATABASE_NAME: "analytics"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka-ns.svc.cluster.local:9092"
  KAFKA_GROUP_ID: "analytics-worker-task"
  KAFKA_TOPIC_TASK: "task-events"
