apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-worker-project
  namespace: analytics-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-worker-project
  template:
    metadata:
      labels:
        app: analytics-worker-project
    spec:
      containers:
      - name: analytics-worker-project
        image: analytics-worker-project:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: analytics-worker-project-secret
              key: MONGODB_URL
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: analytics-worker-project-config
              key: DATABASE_NAME
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: analytics-worker-project-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: KAFKA_GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: analytics-worker-project-config
              key: KAFKA_GROUP_ID
        - name: KAFKA_TOPIC_PROJECT
          valueFrom:
            configMapKeyRef:
              name: analytics-worker-project-config
              key: KAFKA_TOPIC_PROJECT
      restartPolicy: Always
