apiVersion: v1
kind: Secret
metadata:
  name: analytics-worker-project-secret
  namespace: analytics-ns
type: Opaque
stringData:
  MONGODB_URL: "mongodb://root:secret@mongo.analytics-ns.svc.cluster.local:27017"
