apiVersion: v1
kind: Secret
metadata:
  name: task-service-secret
  namespace: task-ns
type: Opaque
stringData:
  db-dsn: "host=task-postgres.task-ns.svc.cluster.local user=taskuser password=secret dbname=taskdb port=5432 sslmode=disable"
