apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: analytics-ns
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: secret
  MONGODB_URL: "mongodb://root:secret@mongo.analytics-ns.svc.cluster.local:27017"
